# Dockerfile for merging lcov reports
FROM node:21-alpine

RUN apk add \
  --update \
  --no-cache \
  --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
  --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
  lcov git openssh

CMD ["/bin/bash"]
